# Generated by Django 5.2.8 on 2025-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonapplication',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='contestapplication',
            name='child_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contestapplication',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessonapplication',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonapplication',
            name='child_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessonapplication',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
