# Generated by Django 5.2.8 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_lessonapplication_preferred_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefbookTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]

