# Generated by Django 5.2.8 on 2025-11-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_refbooktemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestapplication',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonapplication',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
