# Generated by Django 5.2.8 on 2025-11-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contestapplication_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_open',
        ),
        migrations.AddField(
            model_name='subject',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Вместимость группы'),
        ),
        migrations.AddField(
            model_name='subject',
            name='enrolled',
            field=models.PositiveIntegerField(default=0, help_text='Сколько учеников уже записано'),
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('open', 'Набор открыт'), ('closed', 'Набор закрыт')], default='open', help_text='Статус набора', max_length=10),
        ),
    ]
